language: node_js
node_js:
  - 'node'
env:
  - EXTENSION_ID='extension id for publising to CWS'
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      # Create a new release
      #   On cron jobs, or
      #   When triggered via "Trigger build" on Travis
      branch: master
      condition: ($TRAVIS_EVENT_TYPE = api || $TRAVIS_EVENT_TYPE = cron) && ($(git tag -l --points-at HEAD) = "")
