name: Deployment

on:
  schedule:
    - cron: '31 13 * * 3' # Every Wednesday at 13:31 https://crontab.guru/#31_13_*_*_3
  push:
    tags:
      - "20.*"
      - "21.*"
      - "22.*"
      - "23.*"
      - "24.*"

jobs:

  Version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create tag if necessary
        if: github.event_name == 'schedule'
        run: |
          git fetch --tags
          if [[ $(git tag -l --points-at HEAD) = '' ]]; then
            echo '::set-output name=created::yes'
            export VER=$(npx daily-version)
            git tag $VER -m $VER
            git push origin $VER
          fi

  Build:
    needs: Version
    if: github.event_name == 'push' || needs.Version.outputs.created
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm test
    - name: Update extension’s meta
      run: |
        export VER=$(echo "$GITHUB_REF" | sed -e 's/refs\/tags\///')
        echo https://github.com/$GITHUB_REPOSITORY/tree/$VER > distribution/SOURCE_URL
        npm run version
    - uses: actions/upload-artifact@v2
      with:
        path: distribution

  For Chrome:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
    - run: cd artifact && npx chrome-webstore-upload-cli@1 upload --auto-publish
      env:
        EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

  For Firefox:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
    - run: cd artifact && npx web-ext-submit@4
      env:
        WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
