# Copied from https://github.com/notlmn/browser-extension-template/blob/master/.github/workflows/publish.yml
name: Publish

on:
  workflow_dispatch:
  # You can manually trigger a deployment on GitHub.com
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  schedule:
    - cron: '31 13 * * 3'

jobs:
  Version:
    outputs:
      created: ${{ steps.daily-version.outputs.created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - run: npm install
      - run: npm test # This includes the build
      - uses: fregante/daily-version-action@v1
        name: Create tag if necessary
        id: daily-version
      - uses: notlmn/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: '^Meta|^Document|^Readme|^Lint'

  Submit:
    needs: Version
    if: github.event_name == 'workflow_dispatch' || needs.Build.outputs.created
    strategy:
      matrix:
        command:
          - release:amo
          - release:chrome
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm run build
      - name: Update extension’s meta
        run: npm run version -- ${{ steps.daily-version.outputs.version }}
      - run: npm run ${{ matrix.command }}
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
