# Copied from https://github.com/notlmn/browser-extension-template/blob/master/.github/workflows/publish.yml
name: Publish

on:
  workflow_dispatch:
  # You can manually trigger a deployment on GitHub.com
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  schedule:
    - cron: '31 13 * * 3'

jobs:
  Build:
    outputs:
      created: ${{ steps.daily-version.outputs.created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 20
      - run: npm install
      - run: npm test # This includes the build
      - uses: fregante/daily-version-action@v1
        name: Create tag if necessary
        id: daily-version
      - uses: notlmn/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          template: '{commits}'
          exclude: '^Meta|^Document|^Readme|^Lint'
      - name: Update extension’s meta
        env:
          VER: ${{ steps.daily-version.outputs.version }}
        run: |
          echo https://github.com/$GITHUB_REPOSITORY/tree/$VER > distribution/SOURCE_URL.txt
          npm run version
      - uses: actions/upload-artifact@v2
        with:
          path: distribution

  Submit:
    needs: Build
    if: github.event_name == 'workflow_dispatch' || needs.Build.outputs.created
    strategy:
      matrix:
        command:
          - web-ext-submit@4
          - chrome-webstore-upload-cli@1 upload --auto-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - run: cd artifact && npx ${{ matrix.command }}
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
